# Generated by Django 5.2.4 on 2025-07-26 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_branch_servicecounter_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
