# Generated by Django 5.2.4 on 2025-07-26 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_alter_branch_options_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_keys', to='services.branch')),
            ],
            options={
                'verbose_name_plural': 'Kiosk Keys',
            },
        ),
    ]
